import Head from "next/head";
import { Inter } from "next/font/google";
import { FormEvent, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState([]);

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    setLoading(true);

    const form = e.currentTarget;
    const link = (form.elements.namedItem("link") as HTMLInputElement).value;

    const res = await fetch(`/api/get-ai-response?link=${link}`);
    const data = await res.json();

    setData(data.choices[0].text.trim().split("|"));

    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>AI Linker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <form onSubmit={(e) => handleSubmit(e)}>
            <label htmlFor="link">Enter your link</label>

            <input type="link" name="link" id="link" placeholder="https://" />

            <button type="submit">Generate keywords</button>
          </form>

          {loading && <div className="text-white">Please wait...</div>}

          {data.length > 0 &&
            !loading &&
            data.map((tag, index) => <div key={index}>{tag}</div>)}
        </div>
      </main>
    </>
  );
}
